# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Scala CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - uses: graalvm/setup-graalvm@v1
      with:
        java-version: '21'      # See 'Options' for more details
        distribution: 'graalvm' # See 'Supported distributions' for available options
        github-token: ${{ secrets.GITHUB_TOKEN }}
    - uses: sbt/setup-sbt@v1
    - uses: scalacenter/sbt-dependency-submission@v2
    - run: sbt assembly
